source 'https://rubygems.org'

gem 'rails', '3.2.1'
gem 'pg'
gem 'dalli'
gem 'jquery-rails'
gem 'kaminari'
gem 'meta_search'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :development do
  gem 'letter_opener'
end

group :production do
  gem 'thin'
  gem 'foreman'
  gem 'exception_notification'
end

gem 'scaf-generator'
gem 'sorcery'
gem 'simple_form'
gem 'cancan'
gem 'friendly_id'
gem 'squeel'
gem 'dragonfly'
gem 'fog'
gem 'rack-cache', require: 'rack/cache'
gem 'RedCloth'





